### ISSUE TITLE
Run the pandoc formatter

### ISSUE THREAD

**Issue by mmaloney-sf** [chipsalliance/firrtl-spec#151]
Let's run the pandoc formatter:

`$ pandoc --wrap=preserve spec.md -o spec.md`

Additionally, let's make sure we get this integrated into CI.

**Comment by seldridge** [comment]
PR is already ready to add this to CI!

Is it safe for me to run it and merge the PR and create some pain on your open PRs?

**Comment by mmaloney-sf** [comment]
I thought you had posted that, but I was in a rush not to forget it :)

Let me land #145 first and I should be good.
