### ISSUE TITLE
`eq`/`neq` comparison operators missing from table

### ISSUE THREAD

**Issue by programmerjake** [chipsalliance/firrtl-spec#196]
https://github.com/chipsalliance/firrtl-spec/blob/e28204d2176788909efc8405696e68efd78f54e3/spec.md?plain=1#L3657-L3661

**Comment by seldridge** [comment]
👍 Thanks for the report!

**Comment by seldridge** [comment]
Fixed in https://github.com/chipsalliance/firrtl-spec/commit/0e15e532d2c47d84f00daba5a15b0fc4b94b8711.
