### ISSUE TITLE
RFC: Capture the version of the FIRRTL spec in a .fir file

### ISSUE THREAD

**Issue by mwachs5** [chipsalliance/firrtl-spec#27]
As the FIRRTL specification may evolve, it would be nice to know what version of the specification a given .fir file claims to comply with.

Considerations:

- Should this just be a single version, or a range / regex?
- What should be the change on the spec version due to the addition of this version (what are FIRRTL's own versioning rules)?

**Comment by darthscsi** [comment]
A file should only claim one version.  If it uses a subset of the language compatible with multiple versions, it should just specify the least.  But generally, it would be annoying to write an emitter to try to track ranges of versions based on what gets emitted.  Parseres already have to deal with multiple versions, so I don't think we need producers to also.

**Comment by mwachs5** [comment]
> What should be the change on the spec version due to the addition of this version (what are FIRRTL's own versioning rules)?

I documented this in 1.0.0, so presumably adding something as an optional with a default-if-not-specified-is-1.0.0 would bump the MINOR version

**Comment by seldridge** [comment]
Fixed via #30.
