### ISSUE TITLE
Build error: make: *** No rule to make target `build/img/firrtl-folded-module.eps', needed by `build/spec.pdf'.  Stop.

### ISSUE THREAD

**Issue by ilongshan** [chipsalliance/firrtl-spec#32]
When I tried to build the spec on Mac OS, I got the following error:
```
$ make
make: *** No rule to make target `build/img/firrtl-folded-module.eps', needed by `build/spec.pdf'.  Stop.
```

With some digging, I find that the following make target is not executed:
```
%/:
	mkdir -p $@
```

And after I create the the directory of "build/img" manually and make again, the error is gone.

So how to automatically execute the make target when building the spec?

**Comment by ilongshan** [comment]
I am using version 3.81. Yes it works with 4.3. Thanks for pointing out.

**Comment by seldridge** [comment]
I went ahead and just changed this. Everybody is hitting this and the wildcard target isn't that helpful. 🙃

**Comment by ilongshan** [comment]
That is great!
